spring.application.name=retailflow-api
server.port=8080

spring.profiles.active=prodution

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration-days=7

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

cors.allowed.origins=https://retailflow-front.vercel.app,https://retailflow-front-my-projects-sato.vercel.app,http://localhost:5173,http://localhost:3000

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
upload.dir=uploads