spring.application.name=taskflow-api
server.port=8080


# Profile ativo
spring.profiles.active=prodution


# JWT (SEGURO via env var)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


# CORS (padrão, sobrescrito por profiles)
cors.allowed.origins=http://localhost:5173,https://seu-frontend.vercel.app