spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false

cors.allowed.origins=https://retailflow-front.vercel.app,https://retailflow-front-my-projects-sato.vercel.app,http://localhost:5173,http://localhost:3000

logging.level.root=WARN
logging.level.com.taskflow=INFO